name: Deployment2 demo
on: push
jobs:
 Lint:
   runs-on: ubuntu-latest
   steps:
     - name: Get code
       uses: actions/checkout@v4.2.2
     - name: Install dependencies
       run: npm ci
     - name: Lint
       run: npm run lint
 Test:
   runs-on: ubuntu-latest
   steps:
     - name: Get code
       uses: actions/checkout@v4.2.2
     - name: Install dependencies
       run: npm ci
     - name: Test code
       run: npm run test  
 deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Get code
       uses: actions/checkout@v4.2.2
     - name: Install dependencies
       run: npm ci
     - name: Build code
       run: npm run build
     - name: Deploy code
       run: echo "Depoying code"
